name = "cookstack"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]

[env.dev]
vars = { ENV='dev', BASE_URL='http://localhost:8787', GOOGLE_REDIRECT_URL='http://localhost:8787/api/auth/signin/google/callback' }
d1_databases = [
  { binding="DB", database_name='cookstack', database_id='22ec2f35-8298-49db-b1d6-78947a921ed0' }
]

[env.production]
placement = { mode = 'smart' }
vars = { ENV='production', BASE_URL='https://cookstack.korcek.com', GOOGLE_REDIRECT_URL='https://cookstack.korcek.com/api/auth/signin/google/callback' }
d1_databases = [
  { binding="DB", database_name='cookstack', database_id='22ec2f35-8298-49db-b1d6-78947a921ed0' }
]
r2_buckets = [
  { binding="BUCKET", bucket_name="cookstack"}
]